[workspace]
resolver = "3"
members = ["crates/*"]

[workspace.package]
version = "0.1.0"
authors = ["Dominic J Grimaldi <self@grimoutlook.dev>"]
edition = "2024"
readme = "README.md"
repository = "https://github.com/GrimOutlook/whimsi"
license = "MIT"
keywords = ["installer", "msi", "package", "windows"]

[profile.release]
lints = "deny"
